// Copyright 2023 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated for LSP. DO NOT EDIT.
//
// Doc comments in this file are verbatim copies from the upstream LSP
// specification (metaModel.json). Typos, grammar issues, or terminology
// inconsistencies in comments should be reported to
// https://github.com/microsoft/vscode-languageserver-node, not patched here.

package protocol

// Code generated from protocol/metaModel.json at ref dadd73f7fc283b4d0adb602adadcf4be16ef3a7b (hash dadd73f7fc283b4d0adb602adadcf4be16ef3a7b).
// https://github.com/microsoft/vscode-languageserver-node/blob/dadd73f7fc283b4d0adb602adadcf4be16ef3a7b/protocol/metaModel.json
// LSP metaData.version = 3.17.0.

const (
	RPCMethodCancelRequest              = "$/cancelRequest"
	RPCMethodLogTrace                   = "$/logTrace"
	RPCMethodProgress                   = "$/progress"
	RPCMethodSetTrace                   = "$/setTrace"
	RPCMethodIncomingCalls              = "callHierarchy/incomingCalls"
	RPCMethodOutgoingCalls              = "callHierarchy/outgoingCalls"
	RPCMethodRegisterCapability         = "client/registerCapability"
	RPCMethodUnregisterCapability       = "client/unregisterCapability"
	RPCMethodResolveCodeAction          = "codeAction/resolve"
	RPCMethodResolveCodeLens            = "codeLens/resolve"
	RPCMethodResolveCompletionItem      = "completionItem/resolve"
	RPCMethodResolveDocumentLink        = "documentLink/resolve"
	RPCMethodExit                       = "exit"
	RPCMethodInitialize                 = "initialize"
	RPCMethodInitialized                = "initialized"
	RPCMethodResolve                    = "inlayHint/resolve"
	RPCMethodDidChangeNotebookDocument  = "notebookDocument/didChange"
	RPCMethodDidCloseNotebookDocument   = "notebookDocument/didClose"
	RPCMethodDidOpenNotebookDocument    = "notebookDocument/didOpen"
	RPCMethodDidSaveNotebookDocument    = "notebookDocument/didSave"
	RPCMethodShutdown                   = "shutdown"
	RPCMethodEvent                      = "telemetry/event"
	RPCMethodCodeAction                 = "textDocument/codeAction"
	RPCMethodCodeLens                   = "textDocument/codeLens"
	RPCMethodColorPresentation          = "textDocument/colorPresentation"
	RPCMethodCompletion                 = "textDocument/completion"
	RPCMethodDeclaration                = "textDocument/declaration"
	RPCMethodDefinition                 = "textDocument/definition"
	RPCMethodDiagnostic                 = "textDocument/diagnostic"
	RPCMethodDidChange                  = "textDocument/didChange"
	RPCMethodDidClose                   = "textDocument/didClose"
	RPCMethodDidOpen                    = "textDocument/didOpen"
	RPCMethodDidSave                    = "textDocument/didSave"
	RPCMethodDocumentColor              = "textDocument/documentColor"
	RPCMethodDocumentHighlight          = "textDocument/documentHighlight"
	RPCMethodDocumentLink               = "textDocument/documentLink"
	RPCMethodDocumentSymbol             = "textDocument/documentSymbol"
	RPCMethodFoldingRange               = "textDocument/foldingRange"
	RPCMethodFormatting                 = "textDocument/formatting"
	RPCMethodHover                      = "textDocument/hover"
	RPCMethodImplementation             = "textDocument/implementation"
	RPCMethodInlayHint                  = "textDocument/inlayHint"
	RPCMethodInlineCompletion           = "textDocument/inlineCompletion"
	RPCMethodInlineValue                = "textDocument/inlineValue"
	RPCMethodLinkedEditingRange         = "textDocument/linkedEditingRange"
	RPCMethodMoniker                    = "textDocument/moniker"
	RPCMethodOnTypeFormatting           = "textDocument/onTypeFormatting"
	RPCMethodPrepareCallHierarchy       = "textDocument/prepareCallHierarchy"
	RPCMethodPrepareRename              = "textDocument/prepareRename"
	RPCMethodPrepareTypeHierarchy       = "textDocument/prepareTypeHierarchy"
	RPCMethodPublishDiagnostics         = "textDocument/publishDiagnostics"
	RPCMethodRangeFormatting            = "textDocument/rangeFormatting"
	RPCMethodRangesFormatting           = "textDocument/rangesFormatting"
	RPCMethodReferences                 = "textDocument/references"
	RPCMethodRename                     = "textDocument/rename"
	RPCMethodSelectionRange             = "textDocument/selectionRange"
	RPCMethodSemanticTokensFull         = "textDocument/semanticTokens/full"
	RPCMethodSemanticTokensFullDelta    = "textDocument/semanticTokens/full/delta"
	RPCMethodSemanticTokensRange        = "textDocument/semanticTokens/range"
	RPCMethodSignatureHelp              = "textDocument/signatureHelp"
	RPCMethodTypeDefinition             = "textDocument/typeDefinition"
	RPCMethodWillSave                   = "textDocument/willSave"
	RPCMethodWillSaveWaitUntil          = "textDocument/willSaveWaitUntil"
	RPCMethodSubtypes                   = "typeHierarchy/subtypes"
	RPCMethodSupertypes                 = "typeHierarchy/supertypes"
	RPCMethodLogMessage                 = "window/logMessage"
	RPCMethodShowDocument               = "window/showDocument"
	RPCMethodShowMessage                = "window/showMessage"
	RPCMethodShowMessageRequest         = "window/showMessageRequest"
	RPCMethodWorkDoneProgressCancel     = "window/workDoneProgress/cancel"
	RPCMethodWorkDoneProgressCreate     = "window/workDoneProgress/create"
	RPCMethodApplyEdit                  = "workspace/applyEdit"
	RPCMethodCodeLensRefresh            = "workspace/codeLens/refresh"
	RPCMethodConfiguration              = "workspace/configuration"
	RPCMethodDiagnosticWorkspace        = "workspace/diagnostic"
	RPCMethodDiagnosticRefresh          = "workspace/diagnostic/refresh"
	RPCMethodDidChangeConfiguration     = "workspace/didChangeConfiguration"
	RPCMethodDidChangeWatchedFiles      = "workspace/didChangeWatchedFiles"
	RPCMethodDidChangeWorkspaceFolders  = "workspace/didChangeWorkspaceFolders"
	RPCMethodDidCreateFiles             = "workspace/didCreateFiles"
	RPCMethodDidDeleteFiles             = "workspace/didDeleteFiles"
	RPCMethodDidRenameFiles             = "workspace/didRenameFiles"
	RPCMethodExecuteCommand             = "workspace/executeCommand"
	RPCMethodFoldingRangeRefresh        = "workspace/foldingRange/refresh"
	RPCMethodInlayHintRefresh           = "workspace/inlayHint/refresh"
	RPCMethodInlineValueRefresh         = "workspace/inlineValue/refresh"
	RPCMethodSemanticTokensRefresh      = "workspace/semanticTokens/refresh"
	RPCMethodSymbol                     = "workspace/symbol"
	RPCMethodTextDocumentContent        = "workspace/textDocumentContent"
	RPCMethodTextDocumentContentRefresh = "workspace/textDocumentContent/refresh"
	RPCMethodWillCreateFiles            = "workspace/willCreateFiles"
	RPCMethodWillDeleteFiles            = "workspace/willDeleteFiles"
	RPCMethodWillRenameFiles            = "workspace/willRenameFiles"
	RPCMethodWorkspaceFolders           = "workspace/workspaceFolders"
	RPCMethodResolveWorkspaceSymbol     = "workspaceSymbol/resolve"
)
