// Copyright 2023 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated for LSP. DO NOT EDIT.

package protocol

// Code generated from protocol/metaModel.json at ref release/protocol/3.17.6-next.9 (hash c94395b5da53729e6dff931293b051009ccaaaa4).
// https://github.com/microsoft/vscode-languageserver-node/blob/release/protocol/3.17.6-next.9/protocol/metaModel.json
// LSP metaData.version = 3.17.0.

const (
	MethodCancelRequest             = "$/cancelRequest"
	MethodLogTrace                  = "$/logTrace"
	MethodProgress                  = "$/progress"
	MethodSetTrace                  = "$/setTrace"
	MethodIncomingCalls             = "callHierarchy/incomingCalls"
	MethodOutgoingCalls             = "callHierarchy/outgoingCalls"
	MethodRegisterCapability        = "client/registerCapability"
	MethodUnregisterCapability      = "client/unregisterCapability"
	MethodResolveCodeAction         = "codeAction/resolve"
	MethodResolveCodeLens           = "codeLens/resolve"
	MethodResolveCompletionItem     = "completionItem/resolve"
	MethodResolveDocumentLink       = "documentLink/resolve"
	MethodExit                      = "exit"
	MethodInitialize                = "initialize"
	MethodInitialized               = "initialized"
	MethodResolve                   = "inlayHint/resolve"
	MethodDidChangeNotebookDocument = "notebookDocument/didChange"
	MethodDidCloseNotebookDocument  = "notebookDocument/didClose"
	MethodDidOpenNotebookDocument   = "notebookDocument/didOpen"
	MethodDidSaveNotebookDocument   = "notebookDocument/didSave"
	MethodShutdown                  = "shutdown"
	MethodEvent                     = "telemetry/event"
	MethodCodeAction                = "textDocument/codeAction"
	MethodCodeLens                  = "textDocument/codeLens"
	MethodColorPresentation         = "textDocument/colorPresentation"
	// Rename to avoid conflict with MethodCompletion(CompletionItemKind)
	MethodTextDocumentCompletion     = "textDocument/completion"
	MethodDeclaration                = "textDocument/declaration"
	MethodDefinition                 = "textDocument/definition"
	MethodDiagnostic                 = "textDocument/diagnostic"
	MethodDidChange                  = "textDocument/didChange"
	MethodDidClose                   = "textDocument/didClose"
	MethodDidOpen                    = "textDocument/didOpen"
	MethodDidSave                    = "textDocument/didSave"
	MethodDocumentColor              = "textDocument/documentColor"
	MethodDocumentHighlight          = "textDocument/documentHighlight"
	MethodDocumentLink               = "textDocument/documentLink"
	MethodDocumentSymbol             = "textDocument/documentSymbol"
	MethodFoldingRange               = "textDocument/foldingRange"
	MethodFormatting                 = "textDocument/formatting"
	MethodHover                      = "textDocument/hover"
	MethodImplementation             = "textDocument/implementation"
	MethodInlayHint                  = "textDocument/inlayHint"
	MethodInlineCompletion           = "textDocument/inlineCompletion"
	MethodInlineValue                = "textDocument/inlineValue"
	MethodLinkedEditingRange         = "textDocument/linkedEditingRange"
	MethodMoniker                    = "textDocument/moniker"
	MethodOnTypeFormatting           = "textDocument/onTypeFormatting"
	MethodPrepareCallHierarchy       = "textDocument/prepareCallHierarchy"
	MethodPrepareRename              = "textDocument/prepareRename"
	MethodPrepareTypeHierarchy       = "textDocument/prepareTypeHierarchy"
	MethodPublishDiagnostics         = "textDocument/publishDiagnostics"
	MethodRangeFormatting            = "textDocument/rangeFormatting"
	MethodRangesFormatting           = "textDocument/rangesFormatting"
	MethodReferences                 = "textDocument/references"
	MethodRename                     = "textDocument/rename"
	MethodSelectionRange             = "textDocument/selectionRange"
	MethodSemanticTokensFull         = "textDocument/semanticTokens/full"
	MethodSemanticTokensFullDelta    = "textDocument/semanticTokens/full/delta"
	MethodSemanticTokensRange        = "textDocument/semanticTokens/range"
	MethodSignatureHelp              = "textDocument/signatureHelp"
	MethodTypeDefinition             = "textDocument/typeDefinition"
	MethodWillSave                   = "textDocument/willSave"
	MethodWillSaveWaitUntil          = "textDocument/willSaveWaitUntil"
	MethodSubtypes                   = "typeHierarchy/subtypes"
	MethodSupertypes                 = "typeHierarchy/supertypes"
	MethodLogMessage                 = "window/logMessage"
	MethodShowDocument               = "window/showDocument"
	MethodShowMessage                = "window/showMessage"
	MethodShowMessageRequest         = "window/showMessageRequest"
	MethodWorkDoneProgressCancel     = "window/workDoneProgress/cancel"
	MethodWorkDoneProgressCreate     = "window/workDoneProgress/create"
	MethodApplyEdit                  = "workspace/applyEdit"
	MethodCodeLensRefresh            = "workspace/codeLens/refresh"
	MethodConfiguration              = "workspace/configuration"
	MethodDiagnosticWorkspace        = "workspace/diagnostic"
	MethodDiagnosticRefresh          = "workspace/diagnostic/refresh"
	MethodDidChangeConfiguration     = "workspace/didChangeConfiguration"
	MethodDidChangeWatchedFiles      = "workspace/didChangeWatchedFiles"
	MethodDidChangeWorkspaceFolders  = "workspace/didChangeWorkspaceFolders"
	MethodDidCreateFiles             = "workspace/didCreateFiles"
	MethodDidDeleteFiles             = "workspace/didDeleteFiles"
	MethodDidRenameFiles             = "workspace/didRenameFiles"
	MethodExecuteCommand             = "workspace/executeCommand"
	MethodFoldingRangeRefresh        = "workspace/foldingRange/refresh"
	MethodInlayHintRefresh           = "workspace/inlayHint/refresh"
	MethodInlineValueRefresh         = "workspace/inlineValue/refresh"
	MethodSemanticTokensRefresh      = "workspace/semanticTokens/refresh"
	MethodSymbol                     = "workspace/symbol"
	MethodTextDocumentContent        = "workspace/textDocumentContent"
	MethodTextDocumentContentRefresh = "workspace/textDocumentContent/refresh"
	MethodWillCreateFiles            = "workspace/willCreateFiles"
	MethodWillDeleteFiles            = "workspace/willDeleteFiles"
	MethodWillRenameFiles            = "workspace/willRenameFiles"
	MethodWorkspaceFolders           = "workspace/workspaceFolders"
	MethodResolveWorkspaceSymbol     = "workspaceSymbol/resolve"
)
